### ISSUE TITLE
gateway Failed to introspect Class [com.github.xiaoymin.knife4j.spring.configuration.Knife4jAutoConfiguration]

### ISSUE THREAD

**Issue by wudaoshengu** [macrozheng/mall-swarm#146]
网关启动报错， Caused by: java.lang.ClassNotFoundException: javax.servlet.Filter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 64 common frames omitted

**Comment by BlueLeer** [comment]
我已收到  谢谢 我会尽快查看
